export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const REG_START = "REG_START";
export const REG_SUCCESS = "REG_SUCCESS";
export const REG_FAIL = "REG_FAIL";

export const FETCH_HIGHSCORE_START = "FETCH_HIGHSCORE_START";
export const FETCH_HIGHSCORE_SUCCESS = "FETCH_HIGHSCORE_SUCCESS";
export const FETCH_HIGHSCORE_FAIL = "FETCH_HIGHSCORE_FAIL";

export const SET_HIGHSCORE_START = "SET_HIGHSCORE_START";
export const SET_HIGHSCORE_SUCCESS = "SET_HIGHSCORE_SUCCESS";
export const SET_HIGHSCORE_FAIL = "SET_HIGHSCORE_FAIL";
